ShopDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import IndexView, AddProductView, ProductView, CategoryView, CommentView, SignUpUserView, LogoutUserView, SingInUserView

urlpatterns = [
      path('', IndexView),
      path('add/', AddProductView),
      path('product/', ProductView),
      path('category/', CategoryView),
      path('comment/', CommentView),
      path('singin/', SignUpUserView),
      path('singup/', SingInUserView),
      path('logout/', LogoutUserView),
]

main/models.py
from django.db import models
from .utils import valid_prise

# Create your models here.
class Category(models.Model):
      title = models.CharField(max_length=255, verbose_name="Категория")
      created_at = models.DateTimeField(auto_now_add=True,
                                        verbose_name="Дата создания")

      def __str__(self):
            return self.title

      class Meta:
            verbose_name = "Категория"
            verbose_name_plural = "Категории"

class Product(models.Model):
      image = models.ImageField(upload_to='product/')
      title = models.CharField(max_length=250, verbose_name="Название")
      description = models.TextField(verbose_name="Опсание")
      price = models.CharField(default=10.0, verbose_name="Цена",
            validators=[valid_prise], max_length=255)
      category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                   verbose_name="Категория")
      created_at = models.DateTimeField(auto_now_add=True,
                                        verbose_name="Дата создания")

      def __str__(self) -> str:
            return f"{self.title} - {self.category} - {self.created_at}"

      class Meta:
            verbose_name = "Товар"
            verbose_name_plural = "Товары"


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm, TextInput, Textarea, Select, FileInput, EmailInput, PasswordInput
from .models import Category, Product, Comment
from django.contrib.auth.models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "password"]
        widgets = {
            "first_name": TextInput(attrs={
                "class": "form-control text-bg-dark",
                "aria-label": "First name"
            }),
            "last_name": TextInput(attrs={
                "class": "form-control text-bg-dark",
                "aria-label": "Last name",
            }),
            "username": TextInput(attrs={
                "class": "form-control text-bg-dark",
                "aria-label": "Username",
                "aria-describedby": "addon-wrapping",
            }),
            "email": EmailInput(attrs={
                "class": "form-control text-bg-dark",
                "aria-label": "E-mail",
                "aria-describedby": "inputGroup-sizing-default",
            }),
            "password": PasswordInput(attrs={
                "class": "form-control text-bg-dark",
                "aria-label": "Password",
                "aria-describedby": "inputGroup-sizing-default",
            }),
        }

class CategoryForm(ModelForm):
      class Meta:
            model = Category
            fields = ['title']
            widgets = {
                  "title": TextInput(attrs={
                        "style": "margin: 20px; width: 1190px;",
                        "class": "form-control",
                        "placeholder": "Категория"
            })
            }

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['image','title', 'description', 'price', 'category']
        widgets = {
            "image": FileInput(attrs={
                "style": "margin: 20px; width: 1190px;",
                "class": "form-control form-control-dark",
                "placeholder": "Изображение",
            }),
            "title": TextInput(attrs={
                "style": "margin: 20px; width: 1190px;",
                "class": "form-control",
                "placeholder": "Товар",
            }),
            "description": Textarea(attrs={
                "style": "margin: 20px; width: 1190px;",
                "class": "form-control form-control-dark",
                "type": "text",
                "placeholder": "Описание",
                "cols": "30",
                "rows": "10",
            }),
            "price": TextInput(attrs={
                "style": "margin: 20px; width: 1190px;",
                "class": "form-control",
                "placeholder": "Цена",
            }),
            'category': Select(attrs={
                "style": "margin: 20px; width: 1190px;",
                'class': 'form-control form-control-dark'
            }),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'content']

main/views.py
from django.shortcuts import render, redirect
from .models import Category, Product
from .forms import ProductForm, CategoryForm, CommentForm, UserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def IndexView(request):
      return render(request, 'main/index.html')


def ProductView(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'main/product.html', context=context)


def AddProductView(request):
      if request.method == 'POST':
            form = ProductForm(request.POST)
            if form.is_valid():
                  form.save()
                  messages.success(request, "Продукты успешно добавлены!")
            else:
                  messages.error(request, form.errors)
      else:
            form = ProductForm()

      context = {
            'form': form
      }

      return render(request, 'main/addproduct.html', context=context)


def CategoryView(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'main/category.html', context=context)


def CommentView(request):
    products = Product.objects.all()
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.product = Product.objects.get(pk=request.POST['product_id'])
            comment.save()
            form = CommentForm()

    context = {
        'products': products,
        'form': form,
    }
    return render(request, 'main/product.html', context=context)


def LogoutUserView(request):
    logout(request)
    return redirect('/')


def SignUpUserView(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            if user.password != request.POST.get('password2'):
                messages.error(request, "Пароли не совпадают!")
                return redirect('/singup')
            else:
                user.set_password(user.password)
                form.save()
                messages.success(request, "Региcтрация прошла успешна!")
                redirect("/")
    else:
        form = UserForm()
    return render(request, "AuthentificateUser/singup.html", {"form": form})


def SingInUserView(request):
    messages.success(request, 'Thank you for still being with us')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Вы успешно вошли в свой ЛК")
            return redirect('/')
        else:
            messages.error(request, "Неверный пароль")
            return redirect('/singin')
    else:
        return render(request, "AuthentificateUser/singin.html")

def LogoutUserView(request):
    logout(request)
    return redirect('/')

def SingUpUserView(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            if user.password != request.POST.get('password2'):
                messages.error(request, "Пароли не совпадают!")
                return redirect('/singup')
            else:
                user.set_password(user.password)
                form.save()
                messages.success(request, "Резистрация прошла успенно!")
                return redirect("/")
    else:
        form = UserForm()
    return render(request, "AuthenticateUser/signup.html", {"form": form})


def SignInUserView(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username and password:
            try:
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Вы успешно вошли!')
                    return redirect("/")
                else:
                    messages.error(request, 'Неверное имя пользователя или пароль.')
            except Exception:
                messages.error(request, 'Произошла ошибка при аутентификации. Пожалуйста, попробуйте снова.')
        else:
            messages.error(request, 'Пожалуйста, введите имя пользователя и пароль.')

    return render(request, "AuthentficateUser/singin.html")

templates/main/addproduct.html
{% extends 'base.html' %}

{% block title %} Добавить Продукт {% endblock %}

{% block content %}
<form style="margin-top: 20px; margin-bottom: 20px; border-radius: 15px;" class="card shadow-sm text-bg-dark"
      method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.image }}
      {{ form.title }}
      {{ form.description }}
      {{ form.price }}
      {{ form.category }}
      <button class="btn btn-outline-light" style="width: 1190px; margin: 20px;" type="submit">Опубликовать</button>
      <a type="button" href="/" class="btn btn-outline-light"
            style="width: 1190px; margin: 20px; margin-top: 0;">Назад</a>
</form>
{% endblock %}

templates/main/category.html
{% extends 'base.html' %}

{% block title %} Добавить категорию {% endblock %}

{% block content %}
<h1>Добавить категорию</h1>
<form style="margin-top: 20px; margin-bottom: 20px; border-radius: 15px;" class="card shadow-sm text-bg-dark"
      method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
            <label for="id_image">Изображение:</label>
            {{ form.image }}
      </div>
      <div class="form-group">
            <label for="id_title">Заголовок:</label>
            {{ form.title }}
      </div>
      <div class="form-group">
            <label for="id_description">Описание:</label>
            {{ form.description }}
      </div>
      <div class="form-group">
            <label for="id_price">Цена:</label>
            {{ form.price }}
      </div>
      <div class="form-group">
            <label for="id_category">Категория:</label>
            {{ form.category }}
      </div>
      <button class="btn btn-outline-light" style="width: 100%;" type="submit">Опубликовать</button>
      <a type="button" href="/" class="btn btn-outline-light" style="width: 100%; margin-top: 10px;">Назад</a>
</form>
{% endblock %}

templates/main/comment.html
<!DOCTYPE html>
<html lang="en">

<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Document</title>
</head>

<body>
      <h2>Оставить комментарий</h2>
      <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Отправить</button>
      </form>

      <h2>Комментарии</h2>
      {% for comment in product.comments.all %}
      <p>{{ comment.content }}</p>
      {% empty %}
      <p>Нет комментариев</p>
      {% endfor %}
</body>

</html>

templates/main/index.html
{% extends 'base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}

{% endblock %}

templates/main/product.html
{% extends 'base.html' %}

{% block title %} Продукты {% endblock %}

{% block content %}
<main>
      <div class="album py-5 bg-body-tertiary">
            <div class="container">
                  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                        {% for product in products %}
                        <div class="col">
                              <div class="card shadow-sm text-bg-dark">
                                    <img class="bd-placeholder-img card-img-top" width="100%"
                                          src="{{ product.image.url }}" focusable="false">
                                    <div class="card-body">
                                          <h4 class="card-text">{{ product.title }}</h4>
                                          <h6 class="card-text">Категория: {{ product.category }}</h6>
                                          <p class="card-text">{{ product.description }}</p>
                                          <div class="d-flex justify-content-between align-items-center">
                                                <p class="card-text">Цена: {{ product.price }}</p>
                                                <small class="text-body-secondary">{{ product.created_at }}</small>
                                          </div>
                                    </div>
                              </div>
                        </div>
                        {% endfor %}
                  </div>
            </div>
      </div>
</main>
{% endblock %}